import { RenderMode, ServerRoute } from '@angular/ssr';

export const serverRoutes: ServerRoute[] = [
  {
    path: '',
    renderMode: RenderMode.Server,
  },
  {
    path: 'login',
    renderMode: RenderMode.Client,
  },
  {
    path: 'crear-cuenta',
    renderMode: RenderMode.Server,
  },
  {
    path: 'nosotros',
    renderMode: RenderMode.Server,
  },
  {
    path: 'productos',
    renderMode: RenderMode.Server,
  },
  {
    path: 'ubicanos-cliente',
    renderMode: RenderMode.Server,
  },
  {
    path: 'pedidos/pedido-persona-tienda-finalizado/:personaId',
    renderMode: RenderMode.Server,
  },
  {
    path: 'tienda',
    renderMode: RenderMode.Server,
  },

  {
    path: 'tienda/productos-categoria/:nombre',
    renderMode: RenderMode.Prerender,
    getPrerenderParams: async () => {
      return [{ nombre: 'tienda' },
      { nombre: 'tazas-publicitarias' },
      { nombre: 'tomatodos-publicitarios' },
      { nombre: 'vasos-publicitarios' },
      { nombre: 'libretas-publicitarias' },
      { nombre: 'lapiceros-publicitarios' },
      { nombre: 'maquinas-e-insumos' },
      { nombre: 'antiestres' },
      { nombre: 'servicios' },
      { nombre: 'envios' },

      ];

    },
  },
  {
    path: 'tienda/productos-categoria/:nombre/item-producto-persona-online/:productoCodigo',
    renderMode: RenderMode.Prerender,
    getPrerenderParams: async () => {
      return [
        //{ nombre: 'servicios', productoCodigo: 'sr1' },
        //{ nombre: 'servicios', productoCodigo: 'sr2' },
        //{ nombre: 'servicios', productoCodigo: 'sr4' },
        { nombre: 'tazas-publicitarias', productoCodigo: 'tz1' },
        { nombre: 'tazas-publicitarias', productoCodigo: 'tz2' },
        { nombre: 'tazas-publicitarias', productoCodigo: 'tz3' },
        { nombre: 'tazas-publicitarias', productoCodigo: 'tz4' },
        { nombre: 'tazas-publicitarias', productoCodigo: 'tz-c' },
        { nombre: 'tazas-publicitarias', productoCodigo: 'tz-a' },
        { nombre: 'tazas-publicitarias', productoCodigo: 'tz-r' },
        { nombre: 'tazas-publicitarias', productoCodigo: 'tz-n' },
        { nombre: 'tomatodos-publicitarios', productoCodigo: 'tm-i' },
        { nombre: 'vasos-publicitarios', productoCodigo: 'ta-1' },
        { nombre: 'vasos-publicitarios', productoCodigo: 'tm-2' },
        { nombre: 'vasos-publicitarios', productoCodigo: 'ch-1' },
        { nombre: 'tomatodos-publicitarios', productoCodigo: 'mg-1' },
        { nombre: 'maquinas-e-insumos', productoCodigo: 'maq-1' },
        //{ nombre: 'maquinas-e-insumos', productoCodigo: 'mq-1' },
        { nombre: 'maquinas-e-insumos', productoCodigo: 'pl-1' },
        { nombre: 'maquinas-e-insumos', productoCodigo: 'c-1' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'ln-1' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lr-2' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'la-3' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'la-4' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lb-1' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lb-2' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lb-3' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lb-4' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lbc-1' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lbc-2' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lbc-3' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lbc-4' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-im1' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-im-02' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-im3' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-im4' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-pu1' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'li-pu2' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'li-pu3' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'li-pu4' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-eco1' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-eco2' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-eco3' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-eco4' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'li-pus01' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'li-pus02' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'li-pus3' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'li-pus4' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'la-eco2' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'la-eco3' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'la-eco1' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'la-eco4' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'la-me2' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'la-me3' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'la-me4' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'la-me1' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-tr-1' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-tr-2' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-tr-3' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-tr-4' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-ru1' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-ru2' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-ru3' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-ru4' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-cp1' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-cp2' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-cp3' },
        { nombre: 'libretas-publicitarias', productoCodigo: 'lib-ps' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'lap-ba' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'lap-gm' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'lap-gm2' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'lap-gm3' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'lap-gr4' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'lap-gm4' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'lap-gm5' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'lap-pr1' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'lap-tr1' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'lap-tr2' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'lap-tr3' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'lap-tr4' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'lap-vda' },
        { nombre: 'lapiceros-publicitarios', productoCodigo: 'lap-az1' },
        { nombre: 'antiestres', productoCodigo: 'ant-pe' },
        { nombre: 'antiestres', productoCodigo: 'ant-mu' },
        { nombre: 'antiestres', productoCodigo: 'ant-cor' },
        { nombre: 'tomatodos-publicitarios', productoCodigo: 'trm-1' },
        { nombre: 'tomatodos-publicitarios', productoCodigo: 'trm-2' },
        { nombre: 'antiestres', productoCodigo: 'ant-med' },
        { nombre: 'antiestres', productoCodigo: 'ant-min' },
        { nombre: 'tomatodos-publicitarios', productoCodigo: 'ta60' },
        { nombre: 'tomatodos-publicitarios', productoCodigo: 'ta75' },
        //{ nombre: 'envios', productoCodigo: 'envio-1' },
        //{ nombre: 'envios', productoCodigo: 'envio-2' },
        //{ nombre: 'envios', productoCodigo: 'envio-3' },

      ]
    },
  },
  {
    path: 'tienda/pedido-persona-online-finalizado/:personaId',
    renderMode: RenderMode.Server,
  },

  {
    path: '**',
    renderMode: RenderMode.Client
  }
];
